import { useState } from "react";
import { useNavigate } from "react-router-dom";
import FormModal from "../../components/FormModal";
import { apiFetch } from "../../api/api";

function ReportForm({
  formData: initialFormData,
  onChange: externalOnChange,
  onSubmit: externalOnSubmit,
  onClose,
  loading: externalLoading,
  onFileChange,
}) {
  const navigate = useNavigate();
  const [internalFormData, setInternalFormData] = useState({
    ReportName: "",
    Category: "Project",
    GeneratedBy: "",
    Date: "",
    Status: "Pending",
    reportFile: null,
  });

  const formData = initialFormData || internalFormData;
  const onChange = externalOnChange || ((event) => {
    const { name, value } = event.target;
    setInternalFormData((previous) => ({ ...previous, [name]: value }));
  });
  const loading = externalLoading || false;

  const handleSubmit = externalOnSubmit || (async (event) => {
    event.preventDefault();
    try {
      const payload = new FormData();
      Object.entries(formData).forEach(([key, value]) => {
        if (value !== null && value !== "") payload.append(key, value);
      });

      const response = await apiFetch("http://localhost:5000/reports/add", {
        method: "POST",
        body: payload,
      });
      const data = await response.json();
      if (!response.ok) throw new Error(data.message || "Failed to generate report");
      alert("Report generated successfully.");
      navigate("/reports");
    } catch (error) {
      alert(error.message);
    }
  });

  return (
    <div className="page-content">
      <div className="page-header">
        <div>
          <h2>Generate Report</h2>
          <p>Create a detailed summary for the selected project or task category.</p>
        </div>
      </div>

      <FormModal
        title="Generate Report"
        onClose={onClose || (() => navigate("/reports"))}
        onSubmit={handleSubmit}
        submitLabel="Generate Report"
        loading={loading}
      >
        <div className="form-field full-width">
          <label htmlFor="report-name">Report Name</label>
          <input id="report-name" name="ReportName" value={formData.ReportName} onChange={onChange} required />
        </div>
        <div className="form-field">
          <label htmlFor="report-category">Category</label>
          <select id="report-category" name="Category" value={formData.Category} onChange={onChange}>
            <option>Project</option>
            <option>Task</option>
            <option>Bug</option>
            <option>Employee</option>
          </select>
        </div>
        <div className="form-field">
          <label htmlFor="report-generated-by">Generated By</label>
          <input id="report-generated-by" name="GeneratedBy" value={formData.GeneratedBy} onChange={onChange} required />
        </div>
        <div className="form-field">
          <label htmlFor="report-date">Report Date</label>
          <input id="report-date" type="date" name="Date" value={formData.Date} onChange={onChange} required />
        </div>
        <div className="form-field">
          <label htmlFor="report-status">Status</label>
          <select id="report-status" name="Status" value={formData.Status} onChange={onChange}>
            <option>Pending</option>
            <option>Generated</option>
          </select>
        </div>
        <div className="form-field full-width">
          <label htmlFor="report-file">PDF Document</label>
          <input
            id="report-file"
            type="file"
            name="reportFile"
            accept="application/pdf,.pdf"
            onChange={onFileChange || ((event) => {
              const file = event.target.files[0] || null;
              setInternalFormData((previous) => ({ ...previous, reportFile: file }));
            })}
            required
          />
        </div>
      </FormModal>
    </div>
  );
}

export default ReportForm;
