import "./Reports.css";

import {
  HiMagnifyingGlass,
  HiPlus,
  HiDocumentChartBar,
  HiFolderOpen,
  HiClipboardDocumentList,
  HiBugAnt,
  HiEye,
  HiArrowDownTray,
  HiTrash,
} from "react-icons/hi2";

function Reports() {

  /* =========================
      REPORT STATISTICS
  ========================= */

  const reportStats = {

    total: 24,

    projectReports: 8,

    taskReports: 10,

    bugReports: 6,

  };

  /* =========================
      REPORT DATA
  ========================= */

  const reports = [

    {
      id: 1,
      name: "Monthly Project Report",
      category: "Project",
      generatedBy: "Rahul",
      date: "15 Jul 2026",
      status: "Generated",
    },

    {
      id: 2,
      name: "Task Completion Report",
      category: "Task",
      generatedBy: "Priya",
      date: "14 Jul 2026",
      status: "Generated",
    },

    {
      id: 3,
      name: "Bug Analysis Report",
      category: "Bug",
      generatedBy: "John",
      date: "13 Jul 2026",
      status: "Pending",
    },

    {
      id: 4,
      name: "Employee Performance",
      category: "Employee",
      generatedBy: "David",
      date: "12 Jul 2026",
      status: "Generated",
    },

    {
      id: 5,
      name: "Project Timeline Report",
      category: "Project",
      generatedBy: "Sneha",
      date: "11 Jul 2026",
      status: "Generated",
    },

  ];
    return (

    <div className="page-content">

      {/* =========================
          PAGE HEADER
      ========================= */}

      <div className="page-header">

        <div>

          <h2>Reports</h2>

          <p>Generate and manage project performance reports.</p>

        </div>

        <button className="primary-btn">

          <HiPlus />

          Generate Report

        </button>

      </div>

      {/* =========================
          REPORT STATISTICS
      ========================= */}

      <section className="report-stats">

        <div className="report-stat-card">

          <HiDocumentChartBar />

          <div>

            <h3>{reportStats.total}</h3>

            <span>Total Reports</span>

          </div>

        </div>

        <div className="report-stat-card">

          <HiFolderOpen />

          <div>

            <h3>{reportStats.projectReports}</h3>

            <span>Project Reports</span>

          </div>

        </div>

        <div className="report-stat-card">

          <HiClipboardDocumentList />

          <div>

            <h3>{reportStats.taskReports}</h3>

            <span>Task Reports</span>

          </div>

        </div>

        <div className="report-stat-card">

          <HiBugAnt />

          <div>

            <h3>{reportStats.bugReports}</h3>

            <span>Bug Reports</span>

          </div>

        </div>

      </section>

      {/* =========================
          SEARCH & FILTERS
      ========================= */}

      <div className="toolbar">

        <div className="search-box">

          <HiMagnifyingGlass />

          <input
            type="text"
            placeholder="Search report..."
          />

        </div>

        <div className="filters">

          <select>

            <option>All Categories</option>

            <option>Project</option>

            <option>Task</option>

            <option>Bug</option>

            <option>Employee</option>

          </select>

          <select>

            <option>All Status</option>

            <option>Generated</option>

            <option>Pending</option>

          </select>

        </div>

      </div>

      {/* =========================
          REPORT TABLE
      ========================= */}

      <div className="table-card">

        <table>

          <thead>

            <tr>

              <th>Report Name</th>

              <th>Category</th>

              <th>Generated By</th>

              <th>Date</th>

              <th>Status</th>

              <th>Actions</th>

            </tr>

          </thead>

          <tbody>
                        {reports.map((report) => (

              <tr key={report.id}>

                <td>

                  <div className="report-info">

                    <div className="report-avatar">

                      <HiDocumentChartBar />

                    </div>

                    <div>

                      <strong>{report.name}</strong>

                    </div>

                  </div>

                </td>

                <td>{report.category}</td>

                <td>{report.generatedBy}</td>

                <td>{report.date}</td>

                <td>

                  <span
                    className={`status ${report.status
                      .toLowerCase()
                      .replace(/\s/g, "-")}`}
                  >

                    {report.status}

                  </span>

                </td>

                <td>

                  <button className="action view">

                    <HiEye />

                  </button>

                  <button className="action download">

                    <HiArrowDownTray />

                  </button>

                  <button className="action delete">

                    <HiTrash />

                  </button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>

  );

}

export default Reports;