import "./Reports.css";
import { useState } from "react";
import FormModal from "../../components/FormModal";

import {
  HiMagnifyingGlass,
  HiPlus,
  HiDocumentChartBar,
  HiFolderOpen,
  HiClipboardDocumentList,
  HiBugAnt,
  HiEye,
  HiArrowDownTray,
  HiTrash,
} from "react-icons/hi2";

function Reports() {

  /* =========================
      REPORT STATISTICS
  ========================= */

  const reportStats = {

    total: 24,

    projectReports: 8,

    taskReports: 10,

    bugReports: 6,

  };

  /* =========================
      REPORT DATA
  ========================= */

  const reports = [

    {
      id: 1,
      name: "Monthly Project Report",
      category: "Project",
      generatedBy: "Rahul",
      date: "15 Jul 2026",
      status: "Generated",
    },

    {
      id: 2,
      name: "Task Completion Report",
      category: "Task",
      generatedBy: "Priya",
      date: "14 Jul 2026",
      status: "Generated",
    },

    {
      id: 3,
      name: "Bug Analysis Report",
      category: "Bug",
      generatedBy: "John",
      date: "13 Jul 2026",
      status: "Pending",
    },

    {
      id: 4,
      name: "Employee Performance",
      category: "Employee",
      generatedBy: "David",
      date: "12 Jul 2026",
      status: "Generated",
    },

    {
      id: 5,
      name: "Project Timeline Report",
      category: "Project",
      generatedBy: "Sneha",
      date: "11 Jul 2026",
      status: "Generated",
    },

  ];
  const [search,setSearch] = useState("");
  const [showForm, setShowForm] = useState(false);
  const [loading, setLoading] = useState(false);
  const [formData, setFormData] = useState({ ReportName: "", Category: "Project", GeneratedBy: "", Date: "", Status: "Pending" });
  const handleChange = (event) => setFormData((previous) => ({ ...previous, [event.target.name]: event.target.value }));
  const handleSubmit = async (event) => {
    event.preventDefault();
    setLoading(true);
    try {
      const response = await fetch("http://localhost:5000/reports/add", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(formData) });
      const data = await response.json();
      if (!response.ok) throw new Error(data.message || "Failed to generate report");
      setShowForm(false);
    } catch (error) { alert(error.message); } finally { setLoading(false); }
  };
  const filteredReports = reports.filter(({ name, category, generatedBy, status }) =>
  name.toLowerCase().includes(search.trim().toLowerCase()) ||
  category.toLowerCase().includes(search.trim().toLowerCase()) ||
  generatedBy.toLowerCase().includes(search.trim().toLowerCase()) ||
  status.toLowerCase().includes(search.trim().toLowerCase())
);
    return (

    <div className="page-content">

      {/* =========================
          PAGE HEADER
      ========================= */}

      <div className="page-header">

        <div>

          <h2>Reports</h2>

          <p>Generate and manage project performance reports.</p>

        </div>

        <button className="primary-btn" onClick={() => setShowForm(true)}>

          <HiPlus />

          Generate Report

        </button>

      </div>

      {showForm && (
        <FormModal title="Generate Report" onClose={() => setShowForm(false)} onSubmit={handleSubmit} submitLabel="Generate Report" loading={loading}>
          <div className="form-field full-width"><label htmlFor="report-name">Report Name</label><input id="report-name" name="ReportName" value={formData.ReportName} onChange={handleChange} required /></div>
          <div className="form-field"><label htmlFor="report-category">Category</label><select id="report-category" name="Category" value={formData.Category} onChange={handleChange}><option>Project</option><option>Task</option><option>Bug</option><option>Employee</option></select></div>
          <div className="form-field"><label htmlFor="report-generated-by">Generated By</label><input id="report-generated-by" name="GeneratedBy" value={formData.GeneratedBy} onChange={handleChange} required /></div>
          <div className="form-field"><label htmlFor="report-date">Report Date</label><input id="report-date" type="date" name="Date" value={formData.Date} onChange={handleChange} required /></div>
          <div className="form-field"><label htmlFor="report-status">Status</label><select id="report-status" name="Status" value={formData.Status} onChange={handleChange}><option>Pending</option><option>Generated</option></select></div>
        </FormModal>
      )}

      {/* =========================
          REPORT STATISTICS
      ========================= */}

      <section className="report-stats">

        <div className="report-stat-card">

          <HiDocumentChartBar />

          <div>

            <h3>{reportStats.total}</h3>

            <span>Total Reports</span>

          </div>

        </div>

        <div className="report-stat-card">

          <HiFolderOpen />

          <div>

            <h3>{reportStats.projectReports}</h3>

            <span>Project Reports</span>

          </div>

        </div>

        <div className="report-stat-card">

          <HiClipboardDocumentList />

          <div>

            <h3>{reportStats.taskReports}</h3>

            <span>Task Reports</span>

          </div>

        </div>

        <div className="report-stat-card">

          <HiBugAnt />

          <div>

            <h3>{reportStats.bugReports}</h3>

            <span>Bug Reports</span>

          </div>

        </div>

      </section>

      {/* =========================
          SEARCH & FILTERS
      ========================= */}

      <div className="toolbar">

        <div className="search-box">

          <HiMagnifyingGlass />

          <input
            type="text"
            placeholder="Search report..."
          value={search}
          onChange={(e) => setSearch(e.target.value)} />

        </div>

        <div className="filters">

          <select value={search} onChange={(e) => setSearch(e.target.value)}>

            <option value="">All Categories</option>

            <option value="Project">Project</option>

            <option value="Task">Task</option>

            <option value="Bug">Bug</option>

            <option value="Employee">Employee</option>

          </select>

          <select value={search} onChange={(e) => setSearch(e.target.value)}>

            <option value="">All Status</option>

            <option value="Generated">Generated</option>

            <option value="Pending">Pending</option>

          </select>

        </div>

      </div>

      {/* =========================
          REPORT TABLE
      ========================= */}

      <div className="table-card">

        <table>

          <thead>

            <tr>

              <th>Report Name</th>

              <th>Category</th>

              <th>Generated By</th>

              <th>Date</th>

              <th>Status</th>

              <th>Actions</th>

            </tr>

          </thead>

          <tbody>
                        {filteredReports.map((report) => (

              <tr key={report.id}>

                <td>

                  <div className="report-info">

                    <div className="report-avatar">

                      <HiDocumentChartBar />

                    </div>

                    <div>

                      <strong>{report.name}</strong>

                    </div>

                  </div>

                </td>

                <td>{report.category}</td>

                <td>{report.generatedBy}</td>

                <td>{report.date}</td>

                <td>

                  <span
                    className={`status ${report.status
                      .toLowerCase()
                      .replace(/\s/g, "-")}`}
                  >

                    {report.status}

                  </span>

                </td>

                <td>

                  <button className="action view">

                    <HiEye />

                  </button>

                  <button className="action download">

                    <HiArrowDownTray />

                  </button>

                  <button className="action delete">

                    <HiTrash />

                  </button>

                </td>

              </tr>

            ))}

          </tbody>

        </table>

      </div>

    </div>

  );

}

export default Reports;